name: playwright-tests

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - run: npm ci
      name: 'Install Node.js'

    - run: npx playwright install --with-deps
      name: 'Install Playwright browsers'
        
    - run: npx playwright test
      name: 'Run Backend and Frontend tests'
      env:
        CI: 'true'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: playwright-report

  


