name: playwright-tests

on:
  schedule:
    - cron: '30 3,11 * * *'
    # 9:00 AM IST is 3:30 AM UTC.
    # 5:00 PM IST is 11:30 AM UTC.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke_tests:
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    steps:
    - name: 'Checkout main branch'
      uses: actions/checkout@v3
      with:
        ref: 'main'
        
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 'Install dependencies'
      run: npm install

    - name: 'Install Playwright browsers'
      run: npx playwright install --with-deps

    - name: 'Install Java 11 (Required for Allure)'
      run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk   
      
    - name: 'Run Backend and Frontend tests'
      run: npx playwright test
      env:
        CI: 'true'
  
    - name: 'Generate Allure Report'
      run: npx allure generate allure-results --clean --output allure-report
        
    - name: 'Upload a Build Artifact'
      uses: actions/upload-artifact@v4.4.3
      with:
        name: playwright-artifact
        path: |
          playwright-report
          test-results
          traces
      if: always()
    
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-report
